name: pkg_network
description: A starting point for Dart libraries or applications.
version: 1.0.2
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  http: ^1.2.0
  pkg_utils:
    git:
      url: https://github.com/Toph92/pkg_utils
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
